### ISSUE TITLE
When do you set D_HOSTNAME?

### ISSUE THREAD

**Issue by canadaduane** [z0al/dotfiles#1]
Hi! I'm learning about flakes via your repository--I hope it's ok to ask a question!

I noticed you have a [D_HOSTNAME](https://github.com/z0al/dotfiles/blob/main/bin/up#L6) env var in your `up` script. Do you set this manually on your hosts? If so, why not set it automatically? (I was looking around for D_HOSTNAME elsewhere in the repo, and afaict, this is the only reference to it).

Thanks!

**Comment by z0al** [comment]
Hi @canadaduane , I'm glad to hear you've found the repo helpful. I guess moving forward I should keep the repo clean :D 

In nutshell, the `D_HOSTNAME` is a hack that I indent to remove shortly, I advice you to ignore it (btw, the `d` stands for Dotfiles, I use it for to prefix my own modules and custom stuff). 

My work Macbook is managed by my employer. The software it uses seems to force a specific hostname while in my case hostnames are inferred from the file names under `/hosts/darwin`. 

I did not wish to change the file name and since I learned about this recent change mid-workday I added `D_HOSTNAME` as a quick fix to force my own hostname to be used by `up` 🤐 . I have the variable declared in `~/.localrc` which is referenced [here](https://github.com/z0al/dotfiles/blob/b71c3a91d2e526defdadf7748463acc076c14647/home/cli/localrc.nix#L2). I hope that helps.

**Comment by canadaduane** [comment]
I think your structure and arrangement of a multi-system flake is very nice--I'm grateful you've shared it here. And thanks for the explanation!

**Comment by z0al** [comment]
fyi, I finally got around fixing this. I rewrote the [up](https://github.com/z0al/dotfiles/blob/main/bin/up) script in fish and:

* Removed `D_HOSTNAME` in favor of an optional `-h/--host` cli flag. In hosts where I need to override this I simply alias `up` to `up --host <value>` e.g. [here](https://github.com/z0al/dotfiles/blob/05e056a25c3ebf6bc5afc54638affb4369919423/hosts/darwin/contentful.nix#L3-L7)
* I added a `-d/--dotfiles` flag to specify the dotfiles path. It defaults to `~/.dotfiles` as it before.
* Unknown flags are passed down the underlying command. I sometimes find the need to pass additional flags e.g. `--show-trace` to debug an issue, this means I can pass whatever I want (mostly) while keeping `up` implementation minimal.
